flags:
  QuickCheck:
    templatehaskell: false
extra-package-dbs: []
packages:
- satisfaction-core/
- satisfaction/
extra-deps:
- Glob-0.7.5
- QuickCheck-2.8.1
- abstract-deque-0.3
- abstract-par-0.3.3
- aeson-0.11.2.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.0.1
- blaze-builder-0.4.0.1
- cassava-0.4.5.0
- cereal-0.5.1.0
- clock-0.6.0.1
- criterion-1.1.1.0
- dlist-0.7.1.2
- erf-2.0.0.0
- fail-4.9.0.0
- filemanip-0.3.6.3
- hashable-1.2.4.0
- hastache-0.6.1
- ieee754-0.7.6
- math-functions-0.1.5.2
- monad-par-0.3.4.7
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.3.2
- optparse-applicative-0.12.1.0
- parallel-3.2.1.0
- parse-dimacs-1.3
- parsec-3.1.9
- primitive-0.6.1.0
- random-1.1
- regex-base-0.93.2
- regex-tdfa-rc-1.1.8.3
- scientific-0.3.4.4
- statistics-0.13.2.3
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.4
- tasty-0.11.0.2
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- text-1.2.2.0
- tf-random-0.5
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unix-compat-0.4.1.4
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.1.0
- vector-th-unbox-0.2.1.6
resolver: ghc-8.0.1
